spring:
  profiles:
    active: audit
  datasource:
    url: jdbc:oracle:thin:@your-db-host:1521/your-service
    username: your-username
    password: your-password
    driver-class-name: oracle.jdbc.OracleDriver
  batch:
    job:
      enabled: false

logging:
  level:
    root: INFO
    com.example.batch: DEBUG
